server:
  port: 8082

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: pulsbank
    password: pulsbank
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true